import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
import { NextAuthProvider } from "./providers";

import Navbar from '@/components/navbar/Navbar';

export const metadata = {
  title: "P2 Banking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Navbar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
